export const CREATED_SUCCESS_CODE = 201;
export const INCORRECT_DATA_ERROR_CODE = 400;
export const UNAUTHORIZED_ERROR_CODE = 401;
export const FORBIDDEN_ERROR_CODE = 403;
export const NOT_FOUND_ERROR_CODE = 404;
export const CONFLICT_ERROR_CODE = 409;
export const SERVER_ERROR_CODE = 500;
